version: '3.7'
services:
  backend-reinaldo-weather:
    env_file:
      - .env
    container_name: backend-reinaldo-weather
    restart: always
    build:
      context: ./
    environment:
      - WEATHERSTACK_KEY=${WEATHERSTACK_KEY}
      - MAPBOX_KEY=${MAPBOX_KEY}
    volumes:
      - './:/app'
    ports:
      - '5000:3000'
    # 5000 is the one for the local machine, the 3000 is the one that the application opens, but in the container, and that's exposed in the port 5000